var Frames = Object.freeze({
    buttonOff: 'buttonOff',
    buttonOn: 'buttonOn',
    complete: 'complete',
    count: 'count',
    draw: 'draw',
    easterEgg: 'easterEgg',
    error: 'error',
    graphUI: 'graphUI',
    inProgress: 'inProgress',
    label: 'label',
    limiter: 'limiter',
    lotoStep: 'loto-step',
    machineGltf: 'machine-gltf',
    progress: 'progress',
    // pushMe: 'pushMe',
    slider: 'slider',
    slider2d: 'slider-2d',
    sphere: 'sphere',
    sphere2: 'sphere2',
    switch: 'switch',
    testEnvelopeContents: 'test-envelope-contents',
    turtle: 'turtle',
    twoSidedLimiter: 'twoSidedLimiter',
    value: 'value',
    videoCapture: 'videoCapture',
    videoRecording: 'videoRecording',
    warning: 'warning'
});
